 const Packages = [
    {
    "id": "WV71cMMwgy58",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2022-6-4",
    "jumlah_hari": 28,
    "kuota_tersedia": 25,
    "kuota": 22,
    "image_thumbnail": "https://s3-ap-southeast-1.amazonaws.com/mosleme.travel.bucket/mosleme-travels/admin/MjAyMzExMjMwOTQzZVRNU1JFcm1vbExFdg.jpg",
    "price_quad_basic": 42195467,
    "judul_paket": "Haji Plus Premium",
    "maskapaiName": "Batik Air",
    "mendarat_di": "Bandara Sultan Iskandar Muda",
    "hotel_star": 5,
    "packageType": 5
    },
    {
    "id": "WV66cMMwgy68",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2021-2-22",
    "jumlah_hari": 42,
    "kuota_tersedia": 20,
    "kuota": 6,
    "image_thumbnail": "https://source.unsplash.com/random/28",
    "price_quad_basic": 42175885,
    "judul_paket": "Umrah Plus 30 Hari Include 10 hari terakhir ramadhan",
    "maskapaiName": "Trigana Air Service",
    "mendarat_di": "Bandara Internasional Lombok",
    "hotel_star": 2,
    "packageType": 2
    },
    {
    "id": "WV166cMMwgy276",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2022-8-28",
    "jumlah_hari": 24,
    "kuota_tersedia": 25,
    "kuota": 25,
    "image_thumbnail": "https://source.unsplash.com/random/189",
    "price_quad_basic": 12761714,
    "judul_paket": "Haji Plus Premium",
    "maskapaiName": "TransNusa",
    "mendarat_di": "Bandara Internasional Adisutjipto",
    "hotel_star": 2,
    "packageType": 1
    },
    {
    "id": "WV92cMMwgy86",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2021-10-25",
    "jumlah_hari": 8,
    "kuota_tersedia": 46,
    "kuota": 14,
    "image_thumbnail": "https://s3-ap-southeast-1.amazonaws.com/mosleme.travel.bucket/mosleme-travels/admin/MjAyNDAxMjMwNzU5VG9PRU1MdkVtbGVNdA.jpeg",
    "price_quad_basic": 48704478,
    "judul_paket": "Umrah Ramadhan 30 Hari",
    "maskapaiName": "My Indo Airlines",
    "mendarat_di": "Bandara Internasional Yogyakarta",
    "hotel_star": 2,
    "packageType": 3
    },
    {
    "id": "WV169cMMwgy181",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2024-9-16",
    "jumlah_hari": 34,
    "kuota_tersedia": 27,
    "kuota": 3,
    "image_thumbnail": "https://s3-ap-southeast-1.amazonaws.com/mosleme.travel.bucket/mosleme-travels/admin/MjAyMzExMjMwOTQzZVRNU1JFcm1vbExFdg.jpg",
    "price_quad_basic": 43056513,
    "judul_paket": "Badal Haji",
    "maskapaiName": "Lion Air",
    "mendarat_di": "Bandara Internasional Sultan Syarif Kasim II",
    "hotel_star": 3,
    "packageType": 1
    },
    {
    "id": "WV173cMMwgy246",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2023-10-26",
    "jumlah_hari": 2,
    "kuota_tersedia": 3,
    "kuota": 24,
    "image_thumbnail": "https://s3-ap-southeast-1.amazonaws.com/mosleme.travel.bucket/mosleme-travels/admin/MjAyMzEyMDYxNjU1RUVsZWF0VmVTTWVBcg.jpeg",
    "price_quad_basic": 12711081,
    "judul_paket": "Haji Plus Premium",
    "maskapaiName": "Indonesia Air Transport",
    "mendarat_di": "Bandara Internasional Kualanamu",
    "hotel_star": 1,
    "packageType": 4
    },
    {
    "id": "WV128cMMwgy65",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2021-12-3",
    "jumlah_hari": 6,
    "kuota_tersedia": 46,
    "kuota": 21,
    "image_thumbnail": "https://source.unsplash.com/random/231",
    "price_quad_basic": 23525099,
    "judul_paket": "Tabungan Haji 5 Tahun",
    "maskapaiName": "Pelita Air Service",
    "mendarat_di": "Bandara Internasional Ngurah Rai",
    "hotel_star": 5,
    "packageType": 1
    },
    {
    "id": "WV60cMMwgy235",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2024-9-22",
    "jumlah_hari": 23,
    "kuota_tersedia": 15,
    "kuota": 16,
    "image_thumbnail": "https://s3-ap-southeast-1.amazonaws.com/mosleme.travel.bucket/mosleme-travels/admin/MjAyMzExMjMwOTQzZVRNU1JFcm1vbExFdg.jpg",
    "price_quad_basic": 17265506,
    "judul_paket": "Tabungan Haji 5 Tahun",
    "maskapaiName": "My Indo Airlines",
    "mendarat_di": "Bandara Internasional Sultan Thaha",
    "hotel_star": 3,
    "packageType": 2
    },
    {
    "id": "WV280cMMwgy163",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2025-12-12",
    "jumlah_hari": 17,
    "kuota_tersedia": 23,
    "kuota": 14,
    "image_thumbnail": "https://source.unsplash.com/random/208",
    "price_quad_basic": 26041641,
    "judul_paket": "Umrah Plus 30 Hari Include 10 hari terakhir ramadhan",
    "maskapaiName": "Susi Air",
    "mendarat_di": "Bandara Internasional Sultan Syarif Kasim II",
    "hotel_star": 1,
    "packageType": 5
    },
    {
    "id": "WV103cMMwgy273",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2022-5-20",
    "jumlah_hari": 47,
    "kuota_tersedia": 22,
    "kuota": 2,
    "image_thumbnail": "https://s3-ap-southeast-1.amazonaws.com/mosleme.travel.bucket/mosleme-travels/admin/MjAyMzExMjMwOTQzZVRNU1JFcm1vbExFdg.jpg",
    "price_quad_basic": 28143483,
    "judul_paket": "Haji Plus Premium",
    "maskapaiName": "Lion Air",
    "mendarat_di": "Bandara Internasional Sultan Syarif Kasim II",
    "hotel_star": 2,
    "packageType": 2
    },
    {
    "id": "WV68cMMwgy116",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2023-2-7",
    "jumlah_hari": 27,
    "kuota_tersedia": 28,
    "kuota": 2,
    "image_thumbnail": "https://s3-ap-southeast-1.amazonaws.com/mosleme.travel.bucket/mosleme-travels/admin/MjAyMzExMjkxMzE5TG1MbFZvbVN2T0Vhcw.jpeg",
    "price_quad_basic": 33913468,
    "judul_paket": "Promo Badal Haji Quad Exclusive",
    "maskapaiName": "Aviastar",
    "mendarat_di": "Bandara Sultan Syarif Kasim II",
    "hotel_star": 4,
    "packageType": 3
    },
    {
    "id": "WV115cMMwgy209",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2020-7-10",
    "jumlah_hari": 37,
    "kuota_tersedia": 45,
    "kuota": 29,
    "image_thumbnail": "https://source.unsplash.com/random/208",
    "price_quad_basic": 44967598,
    "judul_paket": "Umrah Ramadhan 30 Hari",
    "maskapaiName": "Nusantara Air Charter",
    "mendarat_di": "Bandara Internasional Juanda",
    "hotel_star": 5,
    "packageType": 4
    },
    {
    "id": "WV82cMMwgy156",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2020-3-21",
    "jumlah_hari": 14,
    "kuota_tersedia": 6,
    "kuota": 13,
    "image_thumbnail": "https://source.unsplash.com/random/231",
    "price_quad_basic": 13637467,
    "judul_paket": "Umrah Bersama Ustadz Khalid Basalamah",
    "maskapaiName": "Kalstar Aviation",
    "mendarat_di": "Bandara Ngurah Rai",
    "hotel_star": 2,
    "packageType": 1
    },
    {
    "id": "WV64cMMwgy26",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2021-12-17",
    "jumlah_hari": 38,
    "kuota_tersedia": 21,
    "kuota": 8,
    "image_thumbnail": "https://source.unsplash.com/random/28",
    "price_quad_basic": 22039417,
    "judul_paket": "Tabungan Haji 5 Tahun",
    "maskapaiName": "Xpress Air",
    "mendarat_di": "Bandara Halim Perdana Kusuma",
    "hotel_star": 5,
    "packageType": 2
    },
    {
    "id": "WV206cMMwgy209",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2023-8-14",
    "jumlah_hari": 48,
    "kuota_tersedia": 46,
    "kuota": 5,
    "image_thumbnail": "https://source.unsplash.com/random/127",
    "price_quad_basic": 18322685,
    "judul_paket": "Umrah Bersama Ustadz Khalid Basalamah",
    "maskapaiName": "Wings Air",
    "mendarat_di": "Bandara Internasional Sultan Hasanuddin",
    "hotel_star": 4,
    "packageType": 4
    },
    {
    "id": "WV64cMMwgy87",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2025-5-6",
    "jumlah_hari": 12,
    "kuota_tersedia": 45,
    "kuota": 4,
    "image_thumbnail": "https://source.unsplash.com/random/283",
    "price_quad_basic": 28126512,
    "judul_paket": "Tabungan Haji 5 Tahun",
    "maskapaiName": "My Indo Airlines",
    "mendarat_di": "Bandara Internasional Minangkabau",
    "hotel_star": 1,
    "packageType": 5
    },
    {
    "id": "WV102cMMwgy203",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2020-1-18",
    "jumlah_hari": 46,
    "kuota_tersedia": 41,
    "kuota": 6,
    "image_thumbnail": "https://source.unsplash.com/random/101",
    "price_quad_basic": 40170638,
    "judul_paket": "Umrah Plus 30 Hari Include 10 hari terakhir ramadhan",
    "maskapaiName": "Susi Air",
    "mendarat_di": "Bandara Internasional Sultan Syarif Kasim II",
    "hotel_star": 5,
    "packageType": 2
    },
    {
    "id": "WV263cMMwgy129",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2025-3-15",
    "jumlah_hari": 32,
    "kuota_tersedia": 24,
    "kuota": 4,
    "image_thumbnail": "https://s3-ap-southeast-1.amazonaws.com/mosleme.travel.bucket/mosleme-travels/admin/MjAyMzExMjkxMzE5TG1MbFZvbVN2T0Vhcw.jpeg",
    "price_quad_basic": 22625219,
    "judul_paket": "Umrah Bersama Ustadz Khalid Basalamah",
    "maskapaiName": "Kalstar Aviation",
    "mendarat_di": "Bandara Internasional Kualanamu",
    "hotel_star": 5,
    "packageType": 3
    },
    {
    "id": "WV284cMMwgy234",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2022-8-16",
    "jumlah_hari": 22,
    "kuota_tersedia": 20,
    "kuota": 21,
    "image_thumbnail": "https://source.unsplash.com/random/231",
    "price_quad_basic": 47498371,
    "judul_paket": "Umrah Bersama Ustadz Khalid Basalamah",
    "maskapaiName": "Nam Air",
    "mendarat_di": "Bandara Internasional Juanda",
    "hotel_star": 2,
    "packageType": 3
    },
    {
    "id": "WV72cMMwgy280",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2025-6-5",
    "jumlah_hari": 34,
    "kuota_tersedia": 13,
    "kuota": 24,
    "image_thumbnail": "https://source.unsplash.com/random/127",
    "price_quad_basic": 41154850,
    "judul_paket": "Tour Turki + Umrah",
    "maskapaiName": "Garuda Indonesia",
    "mendarat_di": "Bandara Internasional Minangkabau",
    "hotel_star": 2,
    "packageType": 5
    },
    {
    "id": "WV248cMMwgy29",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2023-3-21",
    "jumlah_hari": 24,
    "kuota_tersedia": 3,
    "kuota": 26,
    "image_thumbnail": "https://source.unsplash.com/random/231",
    "price_quad_basic": 40099230,
    "judul_paket": "Umrah Plus 30 Hari Include 10 hari terakhir ramadhan",
    "maskapaiName": "Wings Air",
    "mendarat_di": "Bandara Internasional Sam Ratulangi",
    "hotel_star": 2,
    "packageType": 4
    },
    {
    "id": "WV199cMMwgy127",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2025-1-4",
    "jumlah_hari": 29,
    "kuota_tersedia": 2,
    "kuota": 13,
    "image_thumbnail": "https://source.unsplash.com/random/101",
    "price_quad_basic": 19405302,
    "judul_paket": "Tabungan Haji 5 Tahun",
    "maskapaiName": "My Indo Airlines",
    "mendarat_di": "Bandara Internasional Sam Ratulangi",
    "hotel_star": 3,
    "packageType": 1
    },
    {
    "id": "WV202cMMwgy118",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2021-11-12",
    "jumlah_hari": 6,
    "kuota_tersedia": 15,
    "kuota": 21,
    "image_thumbnail": "https://source.unsplash.com/random/290",
    "price_quad_basic": 11646449,
    "judul_paket": "Umrah Plus 30 Hari Include 10 hari terakhir ramadhan",
    "maskapaiName": "Indonesia Air Transport",
    "mendarat_di": "Bandara Internasional Yogyakarta",
    "hotel_star": 4,
    "packageType": 1
    },
    {
    "id": "WV265cMMwgy134",
    "kategori": "Himenae osadipiscing",
    "jadwal_keberangkatan": "2023-12-27",
    "jumlah_hari": 5,
    "kuota_tersedia": 5,
    "kuota": 1,
    "image_thumbnail": "https://s3-ap-southeast-1.amazonaws.com/mosleme.travel.bucket/mosleme-travels/admin/MjAyMzEyMDYxNjU1RUVsZWF0VmVTTWVBcg.jpeg",
    "price_quad_basic": 26367891,
    "judul_paket": "Tabungan Haji 5 Tahun",
    "maskapaiName": "NAM Air",
    "mendarat_di": "Bandara Internasional Sultan Aji Muhammad Sulaiman",
    "hotel_star": 1,
    "packageType": 3
    }
    ]

    export default Packages;